import { getFirestore } from "@/src/services/firebase";
import { MarkitEvent } from "@/src/types";

/**
 * Writes a single MarkIt event to:
 *   projects/{projectId}/files/{fileId}/events/{eventId}
 *
 * The event ID is pre-generated by the caller (use a uuid or Firestore auto-id)
 * so that optimistic local state can reference it before the write completes.
 */
export async function addMarkitEvent(
  projectId: string,
  fileId: string,
  event: MarkitEvent,
): Promise<void> {
  await getFirestore()
    .collection("projects")
    .doc(projectId)
    .collection("files")
    .doc(fileId)
    .collection("events")
    .doc(event.id)
    .set(event);
}
