export type ProjectFileType = "image" | "video" | "document";

export interface ProjectFile {
  id: string;
  type: ProjectFileType;
  status: "uploading" | "done" | "error";
  filename: string;
  size: string;
  date: string;
  progress?: number;
  url?: string;
  storagePath?: string;
  mimeType?: string;
  // markit-specific fields — null means the file hasn't been opened in MarkIt yet
  markitStatus?: "active" | "exported";
  exportedUrl?: string;
  // user-editable metadata
  name?: string; // friendly display name — distinct from filename
  notes?: string;
  // Camera EXIF metadata — stored at upload time for future measurement corrections
  exif?: {
    focalLength?: number; // mm — physical focal length of the lens
    focalLengthIn35mmFilm?: number; // mm — 35mm-equivalent focal length (more useful for FOV calc)
    pixelXDimension?: number; // sensor width in pixels
    pixelYDimension?: number; // sensor height in pixels
    make?: string; // device manufacturer e.g. "Apple"
    model?: string; // device model e.g. "iPhone 15 Pro"
    [key: string]: any; // preserve any other EXIF tags for future use
  };
  // AI analysis fields — video only, written by Cloud Function, never by the client
  aiStatus?: "processing" | "analysed" | "error";
  aiError?: string;
  transcript?: string;
  categories?: string[];
  summary?: string;
  analysedAt?: string;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  client_email?: string;
  status?: "draft" | "active" | "completed";
  createdAt?: string;
  updatedAt?: string;
  ownerId: string;
  emailNotifications: boolean;
  notifications: boolean;
  // files are now a Firestore subcollection: projects/{id}/files/{fileId}
  // they are NOT stored on this document anymore
  // client portal
  portalToken?: string; // UUID generated by Cloud Function — never written by the client
  portalActive?: boolean; // kill switch — set to false to revoke access instantly
  // notification preferences — array of ActivityEventType strings the contractor wants push alerts for
  notificationTypes?: string[];
}

export interface PortalSession {
  uid: string;
  email: string | null;
  platforms: Array<"web" | "ios" | "android">;
  firstSeenAt: any; // Firestore Timestamp
  lastSeenAt: any; // Firestore Timestamp
}

export type CreateProjectInput = Omit<Project, "id" | "status" | "createdAt" | "updatedAt">;
export type UpdateProjectInput = Partial<Omit<Project, "id" | "createdAt" | "ownerId">>;
export type WatchProjectsFn = (
  setProjects: (projects: Project[]) => void,
  ownerId: string,
) => () => void;

export type WatchProjectFn = (
  projectId: string,
  setProject: (project: Project) => void,
) => () => void;

export type WatchProjectFilesFn = (
  projectId: string,
  setFiles: (files: ProjectFile[]) => void,
) => () => void;
